[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ------------------------------------
# Shogo
# ------------------------------------
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add='''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

# ------------------------------------
# 見た目系
# ------------------------------------
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
" colorscheme tender
set background=dark
syntax on
set t_Co=256
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
'''

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_add = '''
" colorscheme codedark
colorscheme darkblue
let g:airline_theme = 'codedark'
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# ------------------------------------
# Git系
# ------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# ------------------------------------
# LSP
# ------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
git checkout release
'''
hook_add = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''

# ------------------------------------
# ファイラ
# ------------------------------------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
command! -bang -nargs=* Rg
\ call fzf#vim#grep(
        \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
        \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

# ------------------------------------
# エディタ便利系
# ------------------------------------
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'sirver/ultisnips'
hook_add = '''
" Trigger configuration. You need to change this to something other than <tab> if you use one of the following:
" - https://github.com/Valloric/YouCompleteMe
" - https://github.com/nvim-lua/completion-nvim
let g:UltiSnipsExpandTrigger="<c-k>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
" let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="horizontal"
'''

# ------------------------------------
# Atcoder
# ------------------------------------
[[plugins]]
repo = 'my0k/vim-oj-helper'

