[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ------------------------------------
# Shogo
# ------------------------------------
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add='''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

# ------------------------------------
# 見た目系
# ------------------------------------
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
    " colorscheme tender
    colorscheme xcodewwdc
    set background=dark
    syntax on
    set t_Co=256
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
'''

[[plugins]]
repo = 'lilydjwg/colorizer'

# ------------------------------------
# Git系
# ------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'

# ------------------------------------
# LSP
# ------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''
hook_add = '''
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ coc#refresh()
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
  endfunction
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
'''

# ------------------------------------
# ファイラ
# ------------------------------------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

# ------------------------------------
# エディタ便利系
# ------------------------------------
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'skanehira/translate.vim'

