# ------------------------------------
# toml syntax
# ------------------------------------
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'inkarkat/vim-ingo-library'

[[plugins]]
repo = 'inkarkat/vim-SyntaxRange'
lazy = 1
on_cmd = ['SyntaxIgnore', 'SyntaxInclude']
on_func = ['SyntaxRange']
depends = 'vim-ingo-library'

# ------------------------------------
# AtCoder
# ------------------------------------
# error checker
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_sign_column_always = 1
    let g:ale_fix_on_save = 1
    let g:ale_completion_enabled = 1
    let g:ale_sign_error = '⨉'
    let g:ale_sign_warning = '⚠'
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
    let g:ale_linters = {
        \   'c' : ['clangd'],
        \   'cpp' : ['clangd']
    \}
'''

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
" keymapping
nnoremap <Space>R :wa <bar> :wincmd <bar> :QuickRun <stdin.txt <CR>

let g:quickrun_config = {}

" when you run a cpp file, measure the execution time
let g:quickrun_config['cpp'] = {
\  'cmdopt' : '-std=c++14 -Wall',
\  'hook/time/enable' : 1
\}

let g:quickrun_config['_'] = {
\  'split' : 'vertical'
\}
set splitright
'''
