# ------------------------------------
# toml syntax
# ------------------------------------
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'inkarkat/vim-ingo-library'

[[plugins]]
repo = 'inkarkat/vim-SyntaxRange'
lazy = 1
on_cmd = ['SyntaxIgnore', 'SyntaxInclude']
on_func = ['SyntaxRange']
depends = 'vim-ingo-library'

# ------------------------------------
# toml syntax
# ------------------------------------
[[plugins]]
repo = 'pbondoer/vim-42header'
lazy = 1
on_ft = ['c','js']

# ------------------------------------
# markdown
# ------------------------------------
[[plugins]]
repo = 'plasticboy/vim-markdown'
lazy = 1
on_ft = ['md']
